[project]
name = "br-31"
authors = []
description = ""
telemetry = false
requirements = []
cache_dir = "/Users/sionkim/.clarinet/cache"
[contracts.br-31]
path = "contracts/br-31.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
